ci config updates

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -65,15 +65,16 @@ jobs:
       - run:
           name: "Build and Publish Docker Release Image"
           command: |
-            echo "0.0.0-dev" > tagged.txt
-            if [ ! -f ./tagged.txt ]; then
-                echo "cannot publish a Docker image, release-tag file not found"
-                exit 1
+            echo "Publishing tag '<< pipeline.git.tag >>'"
+            export BUILD_VER="0.0.0-dev"
+            #export BUILD_VER="<< pipeline.git.tag >>"
+            if [ -z "${BUILD_VER}" ]; then
+              echo "cannot publish a Docker image, release-tag is empty"
+              exit 1
             fi
-            export BUILD_VER=$(cat "tagged.txt")
             export BUILD_IMG="kohirens/tmpltoapp:${BUILD_VER}"
             docker build -t "${BUILD_IMG}" --rm -f .docker/Dockerfile --progress plain .
-            docker push "${BUILD_IMG}"
+            #docker push "${BUILD_IMG}"
             docker rm "${BUILD_IMG}"
 
 workflows:
@@ -102,13 +103,11 @@ workflows:
       and:
         - equal: [main, << pipeline.git.branch >>]
         - << pipeline.parameters.triggered_by_bot >>
-        - matches:
-            pattern: "^api|webhook$"
-            value: << pipeline.trigger_source >>
     jobs:
       - vro/tag-and-release:
           context: orb-publishing
-  on-tag-release: # The filter will cause this to ONLY run on release tags.
+
+  on-tag-release:
     jobs:
       - publish-image:
           context: orb-publishing
