add: Auto Build Executables to Pipeline

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -57,7 +57,6 @@ jobs:
   publish-image:
     docker:
       - image: circleci/golang:1.17
-#      - image: kohirens/circle-go:1.17
     steps:
       - setup_remote_docker
       - attach_workspace:
@@ -66,8 +65,8 @@ jobs:
           name: "Build and Publish Docker Release Image"
           command: |
             echo "Publishing tag '<< pipeline.git.tag >>'"
+            export BUILD_VER="<< pipeline.git.tag >>"
             export BUILD_VER="0.0.0-dev"
-            #export BUILD_VER="<< pipeline.git.tag >>"
             if [ -z "${BUILD_VER}" ]; then
               echo "cannot publish a Docker image, release-tag is empty"
               exit 1
@@ -76,6 +75,31 @@ jobs:
             docker build -t "${BUILD_IMG}" --rm -f .docker/Dockerfile --progress plain .
             #docker push "${BUILD_IMG}"
             docker rm "${BUILD_IMG}"
+
+  publish-execs:
+    docker:
+        - image: kohirens/circleci-go:0.2.1
+          auth:
+            username: ${DH_USER}
+            password: ${DH_PASS}
+    steps:
+        - checkout
+        - attach_workspace:
+            at: .
+        - run:
+            name: "Build"
+            command: |
+              echo "Publishing tag '<< pipeline.git.tag >>'"
+              export BUILD_VER="<< pipeline.git.tag >>"
+              if [ -z "${BUILD_VER}" ]; then
+                echo "cannot publish executables, release-tag file not found"
+                exit 1
+              fi
+              go install
+              export PATH="${PATH}:/root/go/bin"
+              go generate
+              chmod +x ./build-gh-artifacts.sh
+              ./build-gh-artifacts.sh
 
 workflows:
   quality-control:
@@ -110,6 +134,10 @@ workflows:
   on-tag-release:
     jobs:
       - publish-image:
+          context: orb-publishing
+          filters:
+            <<: *filter-semantic-tag
+      - publish-execs:
           context: orb-publishing
           filters:
             <<: *filter-semantic-tag
